ci(typescript): update readme.md, license.md and dependency-review.yml
apimatic/apimatic-js-runtime pull request #96
Opened 2023-02-16 09:13 UTC by MaryamAdnan3

- [x] MIT License is added
- [x] Dependency Review is set up.
- [x] ReadMe is refactored.

Closes #95

2023-02-16 09:23 UTC, usamabintariq submitted a review, later dismissed

2023-02-16 09:48 UTC, wajahatiqbal submitted a review, later dismissed

2023-02-17 09:39 UTC, wajahatiqbal requested changes

2023-02-17 09:39 UTC, wajahatiqbal commented on README.md
> +| [@apimatic/file-wrapper](packages/file-wrapper) | Provides file wrapper support to core. |
Wrapper around the file types and their utilities.

2023-02-17 09:39 UTC, wajahatiqbal commented on README.md
> +| [@apimatic/http-headers](packages/http-headers) | Provides http hedaers support to core. |
HTTP Headers utilities for apimatic-js-runtime libraries.

2023-02-17 09:39 UTC, wajahatiqbal commented on README.md
> +| [@apimatic/http-query](packages/http-query) | Provides http query support to core. |
HTTP Query utilities for apimatic-js-runtime libraries

2023-02-17 09:39 UTC, wajahatiqbal commented on README.md
> +| [@apimatic/oauth-adapters](packages/oauth-adapters) | Provides oauth schemes pluggables. |
Provides pluggable adapters for OAth 2.0 authentication schemes.

2023-02-17 09:39 UTC, wajahatiqbal commented on README.md
> +| [@apimatic/xml-adapter](packages/xml-adapter) | Provides xml serialization and deserialization support to core. |
Provides XML serialization and deserialization utilities for apimatic-js-runtime libraries.

2023-02-17 10:28 UTC, usamabintariq approved these changes

2023-02-17 10:35 UTC, wajahatiqbal approved these changes

2023-02-17 11:28 UTC, usamabintariq approved these changes

2023-02-17 11:28 UTC, wajahatiqbal approved these changes

2023-02-17 11:31 UTC, merged